src/Corcel/PostBuilder.php

I just renamed the paginate method to paged. Maybe not the best but the quickest way to get it working with laravel 5 as well as laravel 4.

fixed laravel/lumen 5.x issues

---

src/Corcel/Post.php

Added date fields as Laravel date object

Added date fields as Laravel date object

---

src/Corcel/Author.php
src/Corcel/Post.php
tests/PostTest.php

Added author relationship to model and author relationship to Post. 
Added test for author fields .

Add author relationship to Post model

---

src/Corcel/Term.php
src/Corcel/TermRelationship.php
src/Corcel/TermTaxonomy.php

term taxonomy do not have timestamps

---

README.md
src/Corcel/Post.php

Filter Posts having a specific meta/field.

Add hasMeta scope feature and examples

---

src/Post.php

```
...........................
Time: 532 ms, Memory: 10.00Mb
OK (27 tests, 238 assertions)
```

Add parent relationship to the posts

---

src/Post.php
tests/PostTest.php

Get the `keywords` and a `main_category` of a Post
This is useful to ease SEO stuff

keywords and main_category

---

tests/PostTest.php

```
.............................
Time: 977 ms, Memory: 8.00Mb
OK (29 tests, 200 assertions)
```

Include test to accessors and custom fields

---

src/Post.php

```
.............................
Time: 885 ms, Memory: 8.00Mb
OK (29 tests, 220 assertions)
```

Change meta()->get()-> to meta-> to avoid one more query

---

README.md

```
.............................
Time: 756 ms, Memory: 8.00Mb
OK (29 tests, 272 assertions)
```

Changes in readme and fix typo

---

README.md

Forgot to add this on the dev branch

Add README contributing section

---

src/Term.php
src/TermTaxonomy.php

This is the bugfix for issue #77 
@jgrossi, I think we should create a CorcelModel which redefines the belongsTo/belongsToMany/hasMany, etc... functions to pass the DB connection along, and all our models can extend that class. What do you think ?

Bugfix for issue#77

---

src/Comment.php
src/Model.php
src/User.php
src/UserMetaCollection.php
tests/CommentTest.php

Looking further at Eloquent's code, I've found a solution for the general case that removes the need for listen + notify and localises the fix to 2 methods in Carcel\Model.
I created another test for the comments model to test another type of relationship, it works here too. To get the test passing, I also had to add date support to this model.

Fixing DB connection issue for general case

---

README.md

Update REAMDE with Capitalize P for WordPress

---

src/Comment.php
src/Post.php
src/Traits/CreatedAtTrait.php
src/Traits/UpdatedAtTrait.php

Changed the `CreateAtTrait` and `UpdatedAtTrait` to a specific folder.
```
....................................
Time: 2.49 seconds, Memory: 8.00Mb
OK (36 tests, 379 assertions)
```

Create separate directory to traits

---

tests/PostTest.php

```
.........................................
Time: 2.8 seconds, Memory: 8.00Mb
OK (41 tests, 126 assertions)
```

Limit query in tests to avoid differences in assertions counting

---

tests/TaxonomyTest.php

```
..........................................
Time: 2.52 seconds, Memory: 8.00Mb
OK (42 tests, 129 assertions)
```

Include taxonomies and categories test class

---

src/User.php

added the optimizations from pr #69 to the user model too

---

src/Password/PasswordService.php
src/Post.php
src/Providers/AuthUserProvider.php
tests/AuthenticationTest.php

```
...........................................
Time: 2.5 seconds, Memory: 8.00Mb
OK (43 tests, 130 assertions)
```

Making Auth classes using PSR-2 conventions

---

composer.json
src/Password/PasswordService.php
tests/AuthenticationTest.php

```
...........................................
Time: 1.33 seconds, Memory: 8.00Mb
OK (43 tests, 130 assertions)
```

Using hautelook/phpass version 0.3.4 for hashing purposes

---

src/Password/PasswordService.php

```
...........................................
Time: 1.11 seconds, Memory: 8.00Mb
OK (43 tests, 130 assertions)
```

Change second parameter to true according to WP password settings

---

src/Post.php

This will fix the issue https://github.com/jgrossi/corcel/issues/129 thanks to @rundef

This fix the #129 issue

---

src/User.php

added the optimizations from pull request #69 to the user model too

---

src/Model.php
src/Post.php
src/ThumbnailMeta.php
tests/PostMetaTest.php

Fix issue #107 
```
.............................................
Time: 1.14 seconds, Memory: 10.00Mb
OK (45 tests, 134 assertions)
```

Fix the issue #107

---

README.md
src/Password/PasswordService.php

This fixes the #146 issue with PR #148.

Mergin PR #148

---

src/Post.php
src/User.php
tests/TaxonomyTest.php

- Fix undefined property for User
- Check if ->terms is not null
- Add tests for terms and keywords
```
..............................................
Time: 1.19 seconds, Memory: 10.00MB
OK (46 tests, 136 assertions)
```
See #151 and #1

Fix issue #151

---

tests/TaxonomyTest.php

@jgrossi I think something goes wrong when I call toArray on my $page result. I started unit testing this, and right away the same error messages started again:
```
There was 1 error:
1) TaxonomyTest::testPageToArray
Undefined property: Page::$thumbnail
```

starting to write test for Page->toArray()

---

src/Post.php
tests/PostTest.php

Post parent returns null

---

src/Auth/ResetsPasswords.php
src/Providers/AuthUserProvider.php
src/Providers/Laravel/AuthServiceProvider.php
tests/AuthenticationTest.php

Handle custom user model for authentication

---

src/Post.php
tests/PostTypeTest.php

Post::newFromBuilder : handle arrays

---

src/UserBuilder.php
tests/UserTest.php

Hi guys!
I am re-opening the #199 pull request in `dev` branch and unit test.
I hope to be all according now.
Thanks!
[]'s

Add the "has meta" query condition.

---

README.md

The packagist and downloads link were wrong.
Now to correct branch :smile:

Correcting shield's link

---

composer.json

You can test my fork (maybe you should, just in case!) but finally, updating the dependencies over the composer.json file was all that was really needed!

Update dependencies for Laravel 5.4

---

composer.json

Fix composer.json to allow Laravel 5.4 upgrades

---

src/TermTaxonomy.php

Make terms compatible with meta

Make terms compatible with meta

---

src/Model/User.php
tests/Unit/Model/UserTest.php

Based on `get_avatar_data` function from WordPress: https://developer.wordpress.org/reference/functions/get_avatar_data/#source

Getter for user avatar
