- src/PostBuilder.php
Eloquent supports the whereIn method, but Corcel until now has not made use of it. My use case required me to query multiple post types in the one transaction.
Example:
```php
$posts = Post::typeIn(['post', 'recipe'])->status('publish')->get();
```
> Querying multiple post types

- models/Options.php
- phpunit.xml
- src/Options.php
- tests/OptionsTest.php
```
...........................
Time: 427 ms, Memory: 10.00Mb
OK (27 tests, 226 assertions)
```
- `phpunit.xml` file added so as to ease the testing process
- Options model added with static methods to get options by name or get all
- Options tests
> Options model

- src/PostMeta.php
This is useful when you have Advanced Field Plugins or any other plugin which uses *serialized* values. It keeps the original (serialized) value and adds a new value: The PHP object if it can be unserialized, the original value otherwise
Example (ACF Gallery)
```
2 => array:5 [
"meta_id" => 14
"post_id" => 4
"meta_key" => "cool_gallery"
"meta_value" => "a:2:{i:0;s:1:"9";i:1;s:1:"8";}"
"value" => array:2 [
0 => "9"
1 => "8"
]
]
```
```
...........................
Time: 463 ms, Memory: 10.00Mb
OK (27 tests, 234 assertions)
```
> Unserializes `meta` values whenever it's possible

- src/Attachment.php
Attachments are posts in WP and so there are no dedicated fields in the table for them
```
...........................
Time: 464 ms, Memory: 10.00Mb
OK (27 tests, 242 assertions)
```
> Attachment model which eases the analysis of the information.

- src/Post.php
- src/PostMeta.php
- tests/PostTest.php
Beautify posts
- Adds some new fields like `title`, `slug`... **It doesn't remove the original ones**
- Added new field `image`, looks for the `featured image` if any (`_thumbnail_id` => *Attachment* => `url`)
- New Test
```
............................
Time: 439 ms, Memory: 10.25Mb
OK (28 tests, 274 assertions)
```
There are also some changes that were made by [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) automatically (adding final dots in comments and stuff like that). Do you use that tool? It's quite handy and helps you to automatically beautify your code and make it follow the PSR-2 stardars
> Beautify posts

- src/Post.php
- tests/PostTest.php
- Adds all the terms to the post - tests
```
............................
Time: 452 ms, Memory: 10.75Mb
OK (28 tests, 304 assertions)
```
> Post terms

- src/Post.php
- src/User.php
- tests/PostTest.php
- Eases the access to some fields that are metas like `first_name`
- Fixed problems in the *Post terms*: now there are two arrays, a mapped array (*taxonomy* => *term-slug* => *term-name) and a normal array (*taxonomy* => [*term-names*])
```
............................
Time: 452 ms, Memory: 10.75Mb
OK (28 tests, 324 assertions)
```
> Beautify users

- src/User.php
- src/UserMetaCollection.php
- tests/UserTest.php
- tests/config/autoload.php
- tests/config/corcel-dev-without-prefix.sql
Hi,
(Second pull request lucky... disregard first - new to this).
Regarding issue #77, I have developed a proof-of-concept for a potential fix, restricted to just the Users/UserMeta relationship.
Extending the solution, using Laravel's event dispatcher + a trait could help solve this in the general case i.e watch a model's relations for changes and enforce the same connection on them.
I feel that inheriting all models from Post is a step in the wrong direction - a User isn't a Post. The other option was inheriting from Model and reimplementing the entire set of models. The final, less painful, was extension of all models, adjusting relations manually.
I have added a new DB schema, along with a test and new connection.
> Added proof-of-concept for relations connection problem

- src/Model.php
- tests/PostMetaTest.php
As per #99 this fix adds the use statement to the top of Model to import the Str class
Also added a new test class for PostMeta in order to test that this change works. 
```
Testing started at 21:31 ...
Configuration read from C:\xampp\htdocs\corcel\phpunit.xml
Time: 1.45 seconds, Memory: 8.00Mb
OK (39 tests, 322 assertions)
Process finished with exit code 0
```
> import Str class in Model

- src/Options.php
- src/PostMeta.php
- tests/OptionsTest.php
- tests/PostMetaTest.php
Updated `PostMeta` and `Options` `getValueAttribute` method to handle behaviour of `unserialize` to return false. Relates to #102 
```
Testing started at 20:02 ...
Configuration read from C:\xampp\htdocs\corcel\phpunit.xml
Time: 1.49 seconds, Memory: 8.00Mb
OK (41 tests, 366 assertions)
Process finished with exit code 0
```
> Fix postmeta value

- src/Post.php
- tests/PostTest.php
post_type is fillable for Post
added Test for adding post type as fillable to Post
```
Testing started at 20:38 ...
Configuration read from C:\xampp\htdocs\corcel\phpunit.xml
Time: 1.5 seconds, Memory: 8.00Mb
OK (43 tests, 130 assertions)
Process finished with exit code 0
```
> make post_type fillable for all Post classes

- src/Password/PasswordService.php
Replacing hash_equals() with simple string comparison
> Removing hash_equals() function

- README.md
Include information about how to use `Post::method()` and `App\Post::method()`, fixing the suggestion in #137.
> New instructions using Post and App\Post classes

- src/Password/PasswordService.php
***copy of #145 but to (and from) correct develop branch***
While implementing the PasswordService into my (Laravel 5) project I got a fatal error:
> Fatal error: main(): Failed opening required '/path/to/project/vendor/jgrossi/corcel/src/Password/../../vendor/autoload.php' (include_path='.:/usr/share/php:') in /path/to/project/vendor/jgrossi/corcel/src/Password/PasswordService.php on line 7
Since Laravel already includes /vendor/autoload.php, it's not needed to do this again.
> remove require autoload.php

- src/Post.php
This should fix any problem with something like `Undefined property: App\Post::$var`.
```
.............................................
Time: 1.18 seconds, Memory: 10.00MB
OK (45 tests, 134 assertions)
```
> Inverting order in __get() in Post to avoid missing property errors

- src/Post.php
Fixes issue #162 
Before:
**$ php index.php**
string(74) "select * from `postmeta` where `post_id` is null and `post_id` is not null"
string(52) "select * from `posts` where `posts`.`ID` = ? limit 1"
string(47) "select * from `postmeta` where `post_id` in (?)"
**After:**
$ php index.php
string(52) "select * from `posts` where `posts`.`ID` = ? limit 1"
string(47) "select * from `postmeta` where `post_id` in (?)"
> Make sure Post is loaded before trying to fetch its metas

- src/ThumbnailMeta.php
I'm very unfamiliar with WP, but this appears to work.
Allows ability to get different thumbnail sizes ala `the_post_thumbnail` [ref](https://developer.wordpress.org/reference/functions/the_post_thumbnail/)
I see this mentioned in #184 but the solution was not clear to me.
```php
use Corcel\ThumbnailMeta;
if ($article->thumbnail) {
echo $helper->img(
$article->thumbnail->size(ThumbnailMeta::SIZE_THUMBNAIL),
[
'alt' => $article->thumbnail->attachment->alt,
'id'  => 'image_' . $article->thumbnail->value
]
);
}
```
(`$helper` is just an example using [Aura\Html Image Helper](https://github.com/auraphp/Aura.Html/blob/2.x/README-HELPERS.md#img))
> Add accessor for featured image (post thumbnail) sizes

- src/Options.php
- tests/PostTest.php
By extending directly Eloquent, not in all cases the correct database connection will picked. 
It looks like extending Corcel\Models gives no issues.
> Let Options model extends Model instead of Eloquent

- src/Model.php
When using a multisite solution, sometimes you want to create a model from another site. This means that you have to create a new database connection. With this feature you can set the $connection property (like eloquent models) to your model to get data from another database (or other prefixed table)
```
<?php
namespace App;
use Corcel\Post;
class MyCustomPostType extends Post
{
protected $connection = 'my_other_db';
protected $postType = 'mycustomposttype';
}
> If db connection setted do not search for available connection

- src/Post.php
I see a relationship on the  `Post` object for getting at the `parent`, but I did not see a way for getting children. I also might be confused cuz in WP, I dont see the relevance of parent/child in the post admin. only page.
> Add relationship for Page children

- src/Model/Meta/ThumbnailMeta.php
- tests/Unit/Model/ThumbnailTest.php
> #306 fix - Return full size attachment instead of throwing exception for unknown size

- src/Traits/ShortcodesTrait.php
If we not publish config file Laravel tries to iterate over null. This is causing fatal error: `Invalid argument supplied for foreach()`
> Fixed fatal error in Laravel without publishing config

- src/Model/Attachment.php
Because of #305 we can safely remove `toArray` method from Attachment model
> Removed unnecesary toArray in Attachment model

- src/Model/Post.php
- tests/Unit/Model/PostTest.php
Fixes #326. Now only new instances of Builder will have `post_type` where clause.
> Fix post type nesting
